# Generated by Django 5.0.14 on 2026-06-03 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('icon', models.CharField(max_length=50, verbose_name='Icono de Lucide')),
                ('demand', models.CharField(max_length=50, verbose_name='Etiqueta de Demanda')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('specialty', models.CharField(max_length=200, verbose_name='Especialidad')),
                ('level', models.CharField(max_length=100, verbose_name='Nivel')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Calificación')),
                ('jobs', models.IntegerField(verbose_name='Trabajos realizados')),
                ('distance', models.CharField(max_length=50, verbose_name='Distancia')),
                ('eta', models.CharField(max_length=50, verbose_name='Tiempo de llegada (ETA)')),
                ('response', models.CharField(max_length=50, verbose_name='Tiempo de respuesta')),
                ('punctuality', models.IntegerField(verbose_name='Puntualidad (%)')),
                ('price', models.CharField(max_length=10, verbose_name='Nivel de precio')),
                ('available', models.CharField(max_length=100, verbose_name='Disponibilidad')),
                ('badge', models.CharField(max_length=100, verbose_name='Insignia')),
                ('initials', models.CharField(max_length=5, verbose_name='Iniciales')),
                ('experience', models.CharField(max_length=50, verbose_name='Experiencia')),
                ('location', models.CharField(max_length=200, verbose_name='Ubicación')),
                ('lat', models.FloatField(verbose_name='Latitud')),
                ('lng', models.FloatField(verbose_name='Longitud')),
                ('about', models.TextField(verbose_name='Acerca de')),
                ('portfolio', models.JSONField(default=list, verbose_name='Portafolio (Lista de strings)')),
            ],
            options={
                'verbose_name': 'Profesional',
                'verbose_name_plural': 'Profesionales',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Servicio')),
                ('range', models.CharField(max_length=100, verbose_name='Rango de precio')),
                ('time', models.CharField(max_length=100, verbose_name='Tiempo estimado')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
        ),
    ]
