# Generated by Django 5.0.14 on 2026-06-03 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='professional_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de Django'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='available',
            field=models.CharField(default='Disponible hoy', max_length=100, verbose_name='Disponibilidad'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='badge',
            field=models.CharField(default='Identidad verificada', max_length=100, verbose_name='Insignia'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='distance',
            field=models.CharField(default='0.0 km', max_length=50, verbose_name='Distancia'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='eta',
            field=models.CharField(default='15 min', max_length=50, verbose_name='Tiempo de llegada (ETA)'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='experience',
            field=models.CharField(default='1 año', max_length=50, verbose_name='Experiencia'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='jobs',
            field=models.IntegerField(default=0, verbose_name='Trabajos realizados'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='lat',
            field=models.FloatField(default=-2.1894, verbose_name='Latitud'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='lng',
            field=models.FloatField(default=-79.8891, verbose_name='Longitud'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='price',
            field=models.CharField(default='$$', max_length=10, verbose_name='Nivel de precio'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='punctuality',
            field=models.IntegerField(default=100, verbose_name='Puntualidad (%)'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=5.0, max_digits=3, verbose_name='Calificación'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='response',
            field=models.CharField(default='10 min', max_length=50, verbose_name='Tiempo de respuesta'),
        ),
        migrations.CreateModel(
            name='JobRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título del Trabajo')),
                ('description', models.TextField(verbose_name='Descripción o Problema')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente de Cotización'), ('QUOTED', 'Cotizado'), ('ACCEPTED', 'Aceptado / En Progreso'), ('COMPLETED', 'Completado'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('estimated_price', models.CharField(blank=True, max_length=100, null=True, verbose_name='Precio Estimado')),
                ('estimated_time', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tiempo Estimado')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_made', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
                ('professional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_jobs', to='core.professional', verbose_name='Profesional')),
            ],
            options={
                'verbose_name': 'Solicitud de Trabajo',
                'verbose_name_plural': 'Solicitudes de Trabajo',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrador'), ('PROFESSIONAL', 'Profesional/Trabajador'), ('CLIENT', 'Cliente')], default='CLIENT', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuario',
            },
        ),
    ]
