# Generated by Django 5.0.14 on 2026-06-29 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_professional_user_alter_professional_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='credits',
            field=models.IntegerField(default=3, verbose_name='Créditos'),
        ),
    ]
