# Generated by Django 5.0.14 on 2026-07-03 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Pagado ($)')),
                ('credits_added', models.IntegerField(verbose_name='Créditos Añadidos')),
                ('payment_method', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('DEUNA', 'DeUna')], default='TRANSFERENCIA', max_length=50, verbose_name='Método de Pago')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Recarga')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recharges', to='core.professional', verbose_name='Profesional')),
            ],
            options={
                'verbose_name': 'Recarga de Créditos',
                'verbose_name_plural': 'Historial de Recargas',
                'ordering': ['-created_at'],
            },
        ),
    ]
