# Generated by Django 5.0.14 on 2026-07-06 15:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_recharge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequest',
            name='address',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Sector del trabajo'),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitud del trabajo'),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='lng',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitud del trabajo'),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ultima actualizacion'),
        ),
        migrations.AddField(
            model_name='professional',
            name='coverage_radius_km',
            field=models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Radio de cobertura (km)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='jobrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente de Cotización'), ('QUOTED', 'Cotizado'), ('ACCEPTED', 'Profesional seleccionado'), ('IN_PROGRESS', 'En ejecucion'), ('AWAITING_CONFIRMATION', 'Esperando confirmacion del cliente'), ('COMPLETED', 'Completado'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=30, verbose_name='Estado'),
        ),
        migrations.CreateModel(
            name='AiUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('requests', models.PositiveSmallIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_usage', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(choices=[('TRANSFER', 'Transferencia'), ('DEUNA', 'DeUna'), ('CASH', 'Efectivo')], max_length=20)),
                ('receipt_reference', models.CharField(max_length=200)),
                ('receipt_url', models.URLField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente de verificacion'), ('VERIFIED', 'Verificado'), ('RELEASED', 'Liberado al profesional'), ('REFUNDED', 'Reembolsado')], default='PENDING', max_length=20)),
                ('guarantee_status', models.CharField(choices=[('NOT_REQUESTED', 'No solicitada'), ('PENDING', 'Pendiente'), ('ACTIVE', 'Activa'), ('RESOLVED', 'Resuelta')], default='NOT_REQUESTED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_made', to=settings.AUTH_USER_MODEL)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='core.jobrequest')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments_received', to='core.professional')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=500)),
                ('caption', models.CharField(blank=True, max_length=180)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to='core.professional')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estimated_days', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)])),
                ('message', models.TextField(blank=True, max_length=1000)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Enviada'), ('ACCEPTED', 'Aceptada'), ('REJECTED', 'No seleccionada'), ('WITHDRAWN', 'Retirada')], default='SUBMITTED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='core.jobrequest')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='core.professional')),
            ],
            options={
                'ordering': ['amount', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='selected_quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_for_jobs', to='core.quote', verbose_name='Cotizacion seleccionada'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('punctuality', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('quality', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, max_length=1500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_written', to=settings.AUTH_USER_MODEL)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='core.jobrequest')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verified_reviews', to='core.professional')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='aiusage',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='unique_ai_usage_per_day'),
        ),
        migrations.AddConstraint(
            model_name='quote',
            constraint=models.UniqueConstraint(fields=('job', 'professional'), name='unique_quote_per_professional_job'),
        ),
    ]
