# Generated by Django 5.0.14 on 2026-07-10 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_jobrequest_address_jobrequest_lat_jobrequest_lng_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='admin_observation',
            field=models.TextField(blank=True, max_length=2000, verbose_name='Observación para el administrador'),
        ),
    ]
