"""
Django settings for obraya project.

Generated by 'django-admin startproject' using Django 5.0.14.
"""

from pathlib import Path
import os
import sys
import dj_database_url
from django.core.exceptions import ImproperlyConfigured

BASE_DIR = Path(__file__).resolve().parent.parent

def load_env_file(path):
    if not path.exists():
        return {}
    env = {}
    try:
        content = path.read_text(encoding='utf-8-sig')
        if '\x00' in content:
            content = path.read_text(encoding='utf-16')
    except Exception:
        content = path.read_text(encoding='utf-16')

    for line in content.splitlines():
        line = line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue
        key, value = line.split('=', 1)
        env[key.strip()] = value.strip().strip('"').strip("'")
    return env

ENV = load_env_file(BASE_DIR / '.env')


def get_env(name, default=None):
    return os.environ.get(name) or ENV.get(name, default)


def get_env_list(name, default=''):
    return [
        item.strip()
        for item in get_env(name, default).split(',')
        if item.strip()
    ]


SECRET_KEY = get_env('SECRET_KEY')
if not SECRET_KEY:
    raise ImproperlyConfigured('SECRET_KEY must be configured in Railway or .env.')

DEBUG = get_env('DEBUG', 'False').lower() == 'true'

if not DEBUG and 'test' not in sys.argv:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

ALLOWED_HOSTS = get_env_list(
    'ALLOWED_HOSTS',
    'localhost,127.0.0.1,multi-oficios-production.up.railway.app,obrayajob.com,www.obrayajob.com',
)
CSRF_TRUSTED_ORIGINS = get_env_list(
    'CSRF_TRUSTED_ORIGINS',
    'https://multi-oficios-production.up.railway.app,https://obrayajob.com,https://www.obrayajob.com',
)

GOOGLE_MAPS_API_KEY = get_env('GOOGLE_MAPS_API_KEY', '')
GEMINI_API_KEY = get_env('GEMINI_API_KEY', '')
GEMINI_MODEL = get_env('GEMINI_MODEL', 'gemini-3.5-flash')
GEMINI_DAILY_LIMIT = int(get_env('GEMINI_DAILY_LIMIT', '5'))

# Configuración de Cloudflare R2
R2_ACCESS_KEY_ID = get_env('R2_ACCESS_KEY_ID', '')
R2_SECRET_ACCESS_KEY = get_env('R2_SECRET_ACCESS_KEY', '')
R2_ENDPOINT_URL = get_env('R2_ENDPOINT_URL', '')
R2_BUCKET_NAME = get_env('R2_BUCKET_NAME', '')
R2_PUBLIC_URL = get_env('R2_PUBLIC_URL', '')


INSTALLED_APPS = [
    'core',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Django Allauth
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.facebook',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
    # Allauth Middleware
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'obraya.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'obraya.wsgi.application'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

database_url = os.environ.get('DATABASE_URL') or ENV.get('DATABASE_URL')
if database_url:
    DATABASES['default'] = dj_database_url.parse(database_url, conn_max_age=600)

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

LANGUAGE_CODE = 'es-ec'
TIME_ZONE = 'America/Guayaquil'
USE_I18N = True
USE_TZ = True

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'


if 'test' in sys.argv:
    STORAGES = {
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }
else:
    STORAGES = {
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

SITE_ID = 1

ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_EMAIL_VERIFICATION = 'none'
ACCOUNT_LOGIN_METHODS = {'email', 'username'}
ACCOUNT_LOGOUT_ON_GET = True
LOGIN_REDIRECT_URL = 'feed'
LOGOUT_REDIRECT_URL = 'login'

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APPS': [
            {
                'client_id': get_env('GOOGLE_CLIENT_ID', 'placeholder-google-client-id'),
                'secret': get_env('GOOGLE_CLIENT_SECRET', 'placeholder-google-client-secret'),
                'key': ''
            }
        ],
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'online'},
    },
    'facebook': {
        'APPS': [
            {
                'client_id': get_env('FACEBOOK_CLIENT_ID', 'placeholder-facebook-client-id'),
                'secret': get_env('FACEBOOK_CLIENT_SECRET', 'placeholder-facebook-client-secret'),
                'key': ''
            }
        ],
        'METHOD': 'oauth2',
        'SDK_URL': '//connect.facebook.net/es_LA/sdk.js',
        'SCOPE': ['email', 'public_profile'],
        'FIELDS': ['id', 'email', 'name', 'first_name', 'last_name'],
    }
}

SOCIALACCOUNT_LOGIN_ON_GET = True
LOGIN_URL = 'login'

